apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: finsmartapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: finsmartapi-deployment
  minReplicas: 6
  maxReplicas: 12
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

